### ISSUE TITLE
Implement FromStr trait?

### ISSUE THREAD

**Issue by freswa** [kyrias/windows-timezones#5]
I'd like to parse Windows TZ strings (from ICS files) into Chrono TZs. It seems this would be the perfect place :)
Wdyt?

**Comment by kyrias** [comment]
I think a `FromStr` implementation makes sense, though I've never heard of ICS files using Windows timezone strings.  Can you provide an example?

**Comment by kyrias** [comment]
Ah, seems like [the spec sort of just shrugs and lets you do whatever you want](https://icalendar.org/iCalendar-RFC-5545/3-8-3-1-time-zone-identifier.html).

**Comment by freswa** [comment]
Yeah, seems link Lotus/HCL Notes is doing it's thing here :dagger: 
Thanks a lot! :heart:
