### ISSUE TITLE
Update sqlx to 0.7

### ISSUE THREAD

**Issue by svenstaro** [kyrias/windows-timezones#9]
This just in: https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md#070---2023-06-30

**Comment by kyrias** [comment]
Yeah, I was thinking about that earlier today, and I was annoyed that I hadn't noticed it before releasing 0.2 with the strum bump, but they only _announced_ it after I'd done that.

For now we can probably just bump the dep and release 0.3, though if other people end up using this crate it might make sense to have versioned feature flags for such things in the future.

**Comment by svenstaro** [comment]
I don't think one needs to be overly concerned with _proper_ multi-branch maintenance just yet. :)
